(test (eq? 'a 3) #f)
(test (eq? #t 't) #f)
(test (eq? "abc" 'abc) #f)
(test (eq? "hi" '(hi)) #f)
(test (eq? "()" '()) #f)
(test (eq? #\a #\b) #f)
(test (eq? #t #t) #t)
(test (eq? #f #f) #t)
(test (eq? #f #t) #f)
(test (eq? (cdr '(a)) '()) #t)
(test (eq? 'a 'a) #t)
(test (eq? 'a 'b) #f)
