(test (char=? #\d #\d) #t)
(test (char=? #\A #\a) #f)
(test (char=? #\d #\x) #f)
(test (char=? #\d #\D) #f)
(test (char=? #\a #\a) #t)
(test (char=? #\A #\B) #f)
(test (char=? #\a #\b) #f)
(test (char=? #\9 #\0) #f)
(test (char=? #\A #\A) #t)
(test (char=? #\  #\space) #t)
(let ((i (char->integer #\space)))
  (test (char=? (integer->char i) #\space) #t))
(test (char=? (integer->char (char->integer #\")) #\") #t)
(test (char=? #\x65 #\e) #t)

(test (char=? #\d #\d #\d #\d) #t)
(test (char=? #\d #\d #\x #\d) #f)
(test (char=? #\d #\y #\x #\c) #f)
(test (apply char=? cap-a-to-z) #f)
(test (apply char=? mixed-a-to-z) #f)
(test (apply char=? digits) #f)
(test (char=? #\d #\c #\d) #f)

(test (char=? #\a) 'error)
(test (char=?) 'error)
(test (char=? #\a 0) 'error)
(test (char=? #\a #\b 0) 'error)
