(test (char-ci<=? #\A #\B) #t)
(test (char-ci<=? #\a #\B) #t)
(test (char-ci<=? #\A #\b) #t)
(test (char-ci<=? #\a #\b) #t)
(test (char-ci<=? #\9 #\0) #f)
(test (char-ci<=? #\A #\A) #t)
(test (char-ci<=? #\A #\a) #t)
(test (char-ci<=? #\` #\H) #f)
(test (char-ci<=? #\[ #\m) #f)
(test (char-ci<=? #\j #\`) #t)
(test (char-ci<=? #\\ #\E) #f)
(test (char-ci<=? #\t #\_) #t)
(test (char-ci<=? #\a #\]) #t)
(test (char-ci<=? #\z #\^) #t)

(test (char-ci<=? #\d #\D #\d #\d) #t)
(test (char-ci<=? #\d #\d #\X #\d) #f)
(test (char-ci<=? #\d #\Y #\x #\c) #f)
(test (apply char-ci<=? cap-a-to-z) #t)
(test (apply char-ci<=? mixed-a-to-z) #t)
(test (apply char-ci<=? digits) #t)
(test (char-ci<=? #\d #\c #\d) #f)
(test (char-ci<=? #\b #\c #\a) #f)
(test (char-ci<=? #\b #\c #\C) #t)
(test (char-ci<=? #\b #\C #\e) #t)

(test (char-ci<=? #\b #\a "hi") 'error)
(test (char-ci<=? #\b #\a 0) 'error)
