(test (char-ci>? #\A #\B) #f)
(test (char-ci>? #\a #\B) #f)
(test (char-ci>? #\A #\b) #f)
(test (char-ci>? #\a #\b) #f)
(test (char-ci>? #\9 #\0) #t)
(test (char-ci>? #\A #\A) #f)
(test (char-ci>? #\A #\a) #f)
(test (char-ci>? #\^ #\a) #t)
(test (char-ci>? #\_ #\e) #t)
(test (char-ci>? #\[ #\S) #t)
(test (char-ci>? #\\ #\l) #t)
(test (char-ci>? #\t #\_) #f)
(test (char-ci>? #\a #\]) #f)
(test (char-ci>? #\z #\^) #f)
(test (char-ci>? #\] #\X) #t)

(test (char-ci>? #\d #\D #\d #\d) #f)
(test (char-ci>? #\d #\d #\X #\d) #f)
(test (char-ci>? #\d #\Y #\x #\c) #f)
(test (apply char-ci>? cap-a-to-z) #f)
(test (apply char-ci>? mixed-a-to-z) #f)
(test (apply char-ci>? (reverse mixed-a-to-z)) #t)
(test (apply char-ci>? digits) #f)
(test (char-ci>? #\d #\c #\d) #f)
(test (char-ci>? #\b #\c #\a) #f)
(test (char-ci>? #\d #\C #\a) #t)
